# Generated by Django 4.0.6 on 2022-07-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
