# Generated by Django 4.0.6 on 2022-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=12)),
                ('is_active', models.BooleanField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('occupation', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
