# Generated by Django 4.0.6 on 2022-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecustomer', '0004_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
