# Generated by Django 4.0.6 on 2022-07-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecustomer', '0003_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
