# Generated by Django 4.0.6 on 2022-07-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_transaction_date_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
