# Generated by Django 4.0.6 on 2022-07-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
